/** DO NOT EDIT! This file is generated by @svelte-put/inline-svg vite plugin */
declare module 'svelte/elements' {
	export interface SVGAttributes {
		'inline-src'?:
			`./${string}`
			| `../${string}`
			| 'bungie'
			| 'raid'
			| 'shapes'
			| 'shapes\circle'
			| 'shapes\cone'
			| 'shapes\cube'
			| 'shapes\cylinder'
			| 'shapes\prism'
			| 'shapes\pyramid'
			| 'shapes\sphere'
			| 'shapes\square'
			| 'shapes\triangle';
	}
}
export {};
